packages:
  - apps/*
  - packages/*

allowBuilds:
  '@firebase/util': true
  esbuild: true
  node-llama-cpp: true
  puppeteer: true
  protobufjs: true

minimumReleaseAgeExclude:
  - firestore-database@0.2.0
